[package]
name = "doctorate_rs"
readme = "README.md"
version = "0.1.0"
edition = "2021"
license = "LICENSE"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["tracing"] }
tokio = { version = "1.36", features = ["full"] }
hyper = { version = "1.2", features = ["full"] }
hyper-util = "0.1.3"
serde = { version = "1", features = ["derive"] }
serde_json = {version = "1", features = ["preserve_order"]}
thiserror = "*"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
base64 = "0.22.0"
reqwest = { version = "0.11", features = ["json"] }
constcat = "0.5.0"
futures = "*"

[profile.release]
debug = false
lto = "fat"
strip = "symbols"
panic = "abort"
codegen-units = 1
opt-level = 3
