[package]
name = "terra-ps"
version = "0.5.0-alpha1"
edition = "2021"
description = "Server implementations for a certain Gacha Tower Defense game."
authors = ["Rh", "EnokiUN", "UPON"]
publish = false

[dependencies]
anyhow = "1"
chrono = "0.4"
constcat = "0.5"
subtle-encoding = "0.5"
axum = "0.7"
axum-server = "0.6"
base64 = "0.22"
zip = "1"
uuid = { version = "1.8", features = ["v4", "fast-rng", "macro-diagnostics"] }
rand = { version = "0.8", features = ["std_rng"] }

# Crypto
aes = "0.8"
cbc = { version = "0.1", features = ["std"] }
hex = "0.4"
libaes = "0.7"
ring = "0.17"
md-5 = "0.10"

# HTTP
reqwest = { version = "0.12", features = ["json"] }

# Tokio
tokio = { version = "1.37", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }

# Data serialization
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

# Tracings
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.2", features = ["log-tracer", "std"] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "registry",
    "tracing",
    "tracing-log",
] }

# Tower
tower-http = { version = "0.5", features = ["trace"] }

[[bin]]
name = "terra-ps"
path = "src/main.rs"

[profile.release]

strip = true      # Automatically strip symbols from the binary.
lto = true        # Link-time optimization.
opt-level = 3     # Optimize for speed.
codegen-units = 1 # Maximum size reduction optimizations.
debug = false     # Disable debug information.
rpath = true      # Disable runtime path.
