[package]
name = "doctorate_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["ws"] }
tokio = { version = "1.36", features = ["full"] }
hyper = { version = "1.2", features = ["full"] }
hyper-util = "0.1.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"