[package]
name = "doctorate-rs"
version = "0.1.0"
publish = false

[dependencies]
axum = "0.7"
axum-server = "0.6"
dirs = "5"

# Tokio
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["io"] }

# Data serialization
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

# Tracings
tracing = "0.1.40"
tracing-futures = "0.2.5"
tracing-log = { version = "0.2.0", features = ["log-tracer", "std"] }
tracing-bunyan-formatter = "0.3.9"

[profile.release]
strip = true            # Automatically strip symbols from the binary.
lto = true              # Link-time optimization.
opt-level = 3           # Optimize for speed.
codegen-units = 1       # Maximum size reduction optimizations.