[package]
name = "doctorate-rs"
version = "0.2.1"
edition = "2021"
description = "Server implementations for a certain Gacha Tower Defense game."
build = "build.rs"
authors = ["Rh"]
publish = false

[dependencies]
chrono = "0.4"
constcat = "*"
md-5 = "0.10"
subtle-encoding = "0.5"
ring = "0.17"
axum = "0.7"
axum-server = "0.6"
lazy_static = "1.4"
base64 = "0.22"
zip = "0.10.0-alpha.1"
uuid = { version = "1.8", features = ["v4", "fast-rng", "macro-diagnostics"] }

# HTTP
reqwest = { version = "0.12.0", features = ["json"] }

# Tokio
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["io"] }

# Data serialization
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

# Tracings
tracing = "0.1.40"
tracing-futures = "0.2.5"
tracing-log = { version = "0.2.0", features = ["log-tracer", "std"] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "registry",
    "tracing",
    "tracing-log"
]}

# Tower
tower-http = { version = "0.5", features = ["trace"] }

[build-dependencies]
include_dir = "0.7"

[[bin]]
name = "doctorate-rs"
path = "src/server.rs"

[profile.release]
strip = true            # Automatically strip symbols from the binary.
lto = true              # Link-time optimization.
opt-level = 3           # Optimize for speed.
codegen-units = 1       # Maximum size reduction optimizations.
debug = false           # Disable debug information.
rpath = true            # Disable runtime path.