[package]
name = "doctorate-rs"
version = "0.1.0"
edition = "2021"
description = "Server implementations for a certain Gacha Tower Defense game."
authors = ["Rh"]
publish = false

[dependencies]
chrono = "0.4"
constcat = "*"
ansi_term = "0.12"
axum = "0.7"
axum-server = "0.6"
byteorder = "1.5"
dirs = "5"
dotenv = "0.15"
lazy_static = "1.4"
heck = "0.5"
hex = "0.4"
leb128 = "0.2"
paste = "1.0"
sysinfo = "0.30"


reqwest = { version = "0.12.0", features = ["json"] }

# Tokio
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["io"] }

# Data serialization
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

# Tracings
tracing = "0.1.40"
tracing-futures = "0.2.5"
tracing-log = { version = "0.2.0", features = ["log-tracer", "std"] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "registry",
    "tracing",
    "tracing-log"
]}

tower-http = { version = "0.5", features = ["trace"] }

[dependencies.uuid]
version = "1.8.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[[bin]]
name = "doctorate-rs"
path = "src/server.rs"

[profile.release]
strip = true            # Automatically strip symbols from the binary.
lto = true              # Link-time optimization.
opt-level = 3           # Optimize for speed.
codegen-units = 1       # Maximum size reduction optimizations.
debug = false           # Disable debug information.
rpath = true            # Disable runtime path.