[package]
name = "launcher"
version = "0.1.0"
edition = "2021"
description = ""
authors = ["Rhelvetican", "Sasha"]

[dependencies]
frida.workspace = true
anyhow.workspace = true
terraps = { path = "../terraps" }
