name: Cargo Update

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    cargo-update:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main

            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: stable

            - run: cargo update
            - run: cargo clean
            - run: git config --global user.name 'github-actions[bot]'
            - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            - run: git add -A
            - run: if ! git diff-index --quiet HEAD; then
                  git commit -m "Message here"
                  git push origin main
                  fi
